# Auto-generated by canto because you don't have one.
# Please copy to/create ~/.canto/conf.py

# News Feeds
default_rate(30)    # News feeds
add("http://feeds.feedburner.com/codinghorror")
add("http://feeds.reuters.com/reuters/oddlyEnoughNews")
add("http://feeds.reuters.com/reuters/domesticNews")
add("http://feeds.reuters.com/reuters/scienceNews")
add("http://feeds.reuters.com/reuters/topNews")
add("http://feeds.reuters.com/reuters/sportsNews")
add("http://feeds.reuters.com/reuters/healthNews")
add("http://news.cnet.com/8300-13772_3-52.xml")
add("http://news.cnet.com/8300-30685_3-264.xml")
add("http://news.cnet.com/2547-11386_3-0-5.xml")
add("http://news.cnet.com/8300-13578_3-38.xml")
add("http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml")

# Colors

colors[0] = (145, 234)
colors[1] = (181, 234)
colors[2] = (237, 234)

# Blog Feeds
#default_rate(120)   # Slow blog feeds
#add("http://blog1")
#add("http://blog2")

# Quick Feeds
#default_rate(1)     # Quick feed
#default_keep(100)   # Lots of items could be missed
#add("http://quick1")
#add("http://quick2")

# Discard Policy
never_discard("unread")

# Link Handling
#link_handler("uzbl-browser \"%u\"")
import os
if os.getenv("TERM") == "linux":
    link_handler("elinks \"%u\"", text=True)    # Text-only
else:
    link_handler("uzbl-browser \"%u\"")         # X terminal

# Non-HTML Content
link_handler("mplayer -someoptions \"%u\"", ext="mp3")

# PDF Handling
link_handler("apvlv \"%u\"", ext="pdf", fetch=True)

# Image Handling
image_handler("fbv \"%u\"", text=True, fetch=True)

# Download Handling
#reader_keys['w'] = wget_link("/home/mredd/.canto/downloads")

# Reader Layout
reader_orientation = None       # Default floating
reader_orientation = "left"     # Dedicated left of the item list
reader_orientation = "right"    # Dedicated right of the item list
reader_orientation = "top"      # Dedicated on top of the item list
reader_orientation = "bottom"   # Dedicated under the item list
reader_lines = 10               # Dedicated size of layout

# Layout Hook
def resize_hook (cfg):
    cfg.reader_orientation = "center"
    cfg.reader_lines = cfg.width / 2
    cfg.columns = (cfg.width / 2) / 65

# Download Handling
#reader_keys['w'] = wget_link("/home/mredd/.canto/downloads")


